name: Build

on:
  workflow_call:
    

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            cpp
            src
            build.sh
      
      - name: Setup Android NDK
        run: |
          cd "${HOME}"
          MAJOR_VERSION=30
          directoryName="android-ndk-r${MAJOR_VERSION}"
          wget "https://dl.google.com/android/repository/${directoryName}-linux.zip"
          rm -rf "${directoryName}"
          unzip "${directoryName}-linux.zip"
          rm "${directoryName}-linux.zip"
          NDK_REVISION=$(grep -E '^Pkg\.Revision' "${directoryName}/source.properties" | awk -F '=' '{print $2}' | tr -d ' ')
          echo "${NDK_REVISION}" | grep -qE "^${MAJOR_VERSION}\.[0-9]+(\.[0-9]+)*$" || exit 1
          ANDROID_HOME="${HOME}/Android/Sdk"
          ndkDirectory="${ANDROID_HOME}/ndk"
          ANDROID_NDK_HOME="${ndkDirectory}/${NDK_REVISION}"
          mkdir -p "${ndkDirectory}"
          rm -rf "${ANDROID_NDK_HOME}"
          mv -T "${directoryName}" "${ANDROID_NDK_HOME}"
          echo "ANDROID_NDK_HOME=${ANDROID_NDK_HOME}" >> "${GITHUB_ENV}"
          echo "${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> "${GITHUB_PATH}"
      
      - name: Build
        run: |
          cd "${{ github.workspace }}"
          chmod 744 ./build.sh && ./build.sh
        env:
          TZ: 'Asia/Hong_Kong'
      
      - name: Prepare the artifact
        id: artifact
        run: |
          cd "${{ github.workspace }}"
          artifact="$(basename "$(find Release -type f | sort | tail -1)")"
          echo "artifact=${artifact}" >> "${GITHUB_OUTPUT}"
      
      - name: Upload the artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/Release/${{ steps.artifact.outputs.artifact }}
          archive: false
          if-no-files-found: error